name: biacoo
description: Biacoo Med

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  connectivity: ^3.0.6
  dropdown_date_picker: ^0.1.1+1
  flutter_datetime_picker: ^1.5.0
  pin_code_fields: ^7.3.0
  flutter_launcher_icons: ^0.9.2
  youtube_player_flutter: ^8.0.0
  flutter_rating_bar: ^4.0.0
  path_provider: ^2.0.2
  image_picker: ^0.8.0+3


flutter_icons:
  image_path: "assets/logos/BiaacoB.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300

    - family: OpenSans_semibold
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Semibold.ttf

    - family: Proxima
      fonts:
        - asset: assets/fonts/Proxima/ProximaNova-Regular.otf
          weight: 500
        - asset: assets/fonts/Proxima/Proxima-Nova-Bold.otf
          weight: 700
        - asset: assets/fonts/Proxima/Proxima-Nova-Thin.otf
          weight: 300

  assets:
    - assets/logos/biacoowhite.svg
    - assets/logos/biacoocolor.svg
    - assets/icons/pakflag.png
    - assets/icons/phone.png
    - assets/icons/dropdown.png
    - assets/icons/sms.png
    - assets/icons/call.png
    - assets/icons/appointment.png
    - assets/icons/home.png
    - assets/icons/notification.png
    - assets/icons/order.png
    - assets/icons/profile.png
    - assets/icons/fb.png
    - assets/icons/tw.png
    - assets/icons/google.png
    - assets/icons/apple.png
    - assets/icons/mic.png
    - assets/icons/doctor.png
    - assets/icons/doccall.png
    - assets/icons/docapp.png
    - assets/icons/send.png
    - assets/icons/doc.png
    - assets/icons/cap.png
    - assets/icons/injection.png
    - assets/logos/BiaacoB.png
    - assets/icons/cardio.png
    - assets/icons/dentist.png
    - assets/icons/dermatology.png
    - assets/icons/general.png
    - assets/icons/r1.png
    - assets/icons/r2.png
    - assets/icons/r3.png
    - assets/icons/r4.png
    - assets/icons/cancer.png
    - assets/icons/signal.png
    - assets/icons/check.png
    - assets/icons/headphone.png
    - assets/icons/pharmacylab.png
    - assets/icons/plogo.png
    - assets/icons/Cardiovascular.png
    - assets/icons/Electrolytes.png
    - assets/icons/Endocrine.png
    - assets/icons/Gastrointestinal.png
    - assets/icons/AB Screen.png
    - assets/icons/ABG.png
    - assets/icons/CBC.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
